# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: go test -v ./...
        
      - name: golintr
        uses: norwd/golintr@v2.1.0
        
  docker:
    runs-on: ubuntu-latest
    needs: 
    - build
    - test
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0

